import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile} from 'node:fs/promises';
import worker,{detectFile} from '../worker/index.mjs';
import {validatePortfolio,publicPortfolio,preserveSlugs,safeUrl} from '../src/schema.mjs';
import {home,projects,detail,shell} from '../src/render.mjs';
import seed from '../content/portfolio.json' with {type:'json'};
const hash=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('base64url');
const migration=await readFile(new URL('../migrations/0001_content.sql',import.meta.url),'utf8');
function db(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(migration);const prepare=sql=>{let values=[];return{bind(...args){values=args;return this},async first(){return sqlite.prepare(sql).get(...values)||null},async run(){const r=sqlite.prepare(sql).run(...values);return{meta:{changes:r.changes}}}}};return{prepare,async batch(statements){return Promise.all(statements.map(s=>s.run()))},sqlite}}
async function env(){const DB=db(),stored=new Map();const MEDIA={async put(k,v,meta){stored.set(k,{body:v,httpEtag:'test-etag',customMetadata:meta.customMetadata,writeHttpMetadata(h){h.set('Content-Type',meta.httpMetadata.contentType)}})},async get(k){return stored.get(k)},async head(k){return stored.has(k)?{}:null}};const e={DB,MEDIA,GITHUB_CLIENT_ID:'test-client',GITHUB_CLIENT_SECRET:'test-secret',GITHUB_CONTENT_TOKEN:'test-content-token',OWNER_GITHUB_ID:'94220344',ADMIN_ORIGIN:'https://admin.alhuzali.com',PUBLIC_ORIGIN:'https://alhuzali.com',GITHUB_OWNER:'hussamalhuzali',GITHUB_REPO:'alhuzali-portfolio',GITHUB_BRANCH:'main'};const token='a'.repeat(43);await DB.prepare('INSERT INTO sessions VALUES (?, ?, ?, ?)').bind(await hash(token),e.OWNER_GITHUB_ID,'test-csrf',Date.now()+60000).run();return{...e,token,stored}}
function request(path,env,{method='GET',data,auth=true,origin='https://admin.alhuzali.com',csrf='test-csrf',body,headers={}}={}){return new Request('https://admin.alhuzali.com'+path,{method,headers:{...(auth?{Cookie:'__Host-portfolio_session='+env.token}:{}),Origin:origin,'X-CSRF-Token':csrf,...(data?{'Content-Type':'application/json'}:{}),...headers},...(data?{body:JSON.stringify(data)}:body?{body}:{})})}
const call=(path,env,opts)=>worker.fetch(request(path,env,opts),env);
test('CV content validates and draft projects are excluded from publication',()=>{const d=structuredClone(seed);validatePortfolio(d);d.projects[0].published=false;const p=publicPortfolio(d);assert.equal(p.projects.length,3);assert.equal(d.projects.length,4)});
test('URL validation blocks script URLs, credentialed URLs, and spoofed Power BI hosts',()=>{for(const v of ['javascript:alert(1)','//evil.example','https://a:b@example.com','data:text/html,test'])assert.equal(safeUrl(v),false);assert.equal(safeUrl('https://app.powerbi.com.evil.example/view?r=x',{embed:true}),false);assert.equal(safeUrl('https://app.powerbi.com/view?r=x',{embed:true}),true)});
test('renaming preserves prior links and reserves system routes',()=>{const d=structuredClone(seed);d.projects[0].slug='intelligence-platform';preserveSlugs(d,seed);assert.deepEqual(d.projects[0].previousSlugs,['ntdp-intelligence']);d.projects[0].slug='projects';assert.throws(()=>validatePortfolio(d),/reserved/)});
test('renderer escapes authored text without injecting scripts',()=>{const d=structuredClone(seed);d.profile.headline='<script>alert(1)</script>';assert.ok(home(d).includes('&lt;script&gt;'));assert.ok(!home(d).includes('<script>alert'));assert.ok(detail(seed,seed.projects[0]).includes('TARGET AUDIENCE'));assert.ok(projects(seed).includes('id="type-filter"'))});
test('admin fails closed when configuration is missing',async()=>{const r=await worker.fetch(new Request('https://admin.alhuzali.com/api/content'),{});assert.equal(r.status,503);const s=await worker.fetch(new Request('https://admin.alhuzali.com/api/session'),{});assert.deepEqual(await s.json(),{configured:false,authenticated:false})});
test('unauthenticated and forged sessions cannot read drafts or upload',async()=>{const v=await env();for(const path of ['/api/content','/preview/'])assert.equal((await call(path,v,{auth:false})).status,401);assert.equal((await call('/api/upload',v,{method:'POST',auth:false,body:'test'})).status,401);v.token='b'.repeat(43);assert.equal((await call('/api/content',v)).status,401)});
test('cross-origin mutations and invalid CSRF are rejected',async()=>{const v=await env();assert.equal((await call('/api/content',v,{method:'PUT',data:{},origin:'https://evil.example'})).status,403);assert.equal((await call('/api/content',v,{method:'PUT',data:{},csrf:'wrong'})).status,403)});
test('draft edits persist; stale edits cannot overwrite a newer revision',async()=>{const v=await env(),initial=await(await call('/api/content',v)).json();const d=initial.content;d.profile.headline='Clarity through data.';let r=await call('/api/content',v,{method:'PUT',data:{content:d,revision:initial.revision}});assert.equal(r.status,200);assert.equal((await r.json()).revision,2);r=await call('/api/content',v,{method:'PUT',data:{content:d,revision:initial.revision}});assert.equal(r.status,409);assert.equal((await(await call('/api/content',v)).json()).content.profile.headline,'Clarity through data.')});
test('invalid report URLs cannot be saved',async()=>{const v=await env(),d=structuredClone(seed);d.projects[0].type='interactive';d.projects[0].embedUrl='https://example.com/report';const r=await call('/api/content',v,{method:'PUT',data:{content:d,revision:1}});assert.equal(r.status,400)});
test('uploads stay private until a publication references them',async()=>{const v=await env();const r=await call('/api/upload',v,{method:'POST',body:'%PDF-1.7 test','headers':{'X-File-Name':'sample.pdf','Content-Type':'application/pdf'}});assert.equal(r.status,201);const f=await r.json(),path=new URL(f.url).pathname;assert.equal((await call(path,v,{auth:false})).status,404);assert.equal((await call(path,v)).status,200);const d=structuredClone(seed);d.projects[0].documents=[{title:'Sample',kind:'PDF',url:f.url}];await v.DB.prepare("UPDATE studio_content SET published = ? WHERE id = 'portfolio'").bind(JSON.stringify(d)).run();const publicFile=await call(path,v,{auth:false});assert.equal(publicFile.status,200);assert.equal(publicFile.headers.get('Content-Type'),'application/pdf')});
test('unsafe and mismatched upload formats are rejected',()=>{assert.throws(()=>detectFile(new TextEncoder().encode('<script>bad</script>'),'test.pdf'));assert.throws(()=>detectFile(new TextEncoder().encode('<svg/>'),'test.svg'));assert.equal(detectFile(new TextEncoder().encode('%PDF-1.7'),'test.pdf').mime,'application/pdf')});
test('publish commits only public content and records its commit',async()=>{const v=await env();let initial=await(await call('/api/content',v)).json();initial.content.projects[0].published=false;await call('/api/content',v,{method:'PUT',data:{content:initial.content,revision:initial.revision}});const original=globalThis.fetch;let sent;globalThis.fetch=async(url,options={})=>{if(options.method==='PUT'){sent=JSON.parse(options.body);return Response.json({commit:{sha:'abc123'}})}return Response.json({sha:'old',content:Buffer.from(JSON.stringify(seed)).toString('base64')})};try{const r=await call('/api/publish',v,{method:'POST',data:{revision:2}});assert.equal(r.status,200);assert.equal(JSON.parse(Buffer.from(sent.content,'base64').toString()).projects.length,3);assert.equal((await r.json()).commit,'abc123');const current=await(await call('/api/content',v)).json();assert.equal(current.content.projects.length,4);assert.equal(current.commit,'abc123')}finally{globalThis.fetch=original}});
test('OAuth rejects mismatched state and non-owner GitHub identity',async()=>{const v=await env();assert.equal((await call('/auth/callback?state=x&code=y',v)).status,403);const login=await call('/auth/login',v,{auth:false});assert.equal(login.status,302);const url=new URL(login.headers.get('Location'));assert.equal(url.searchParams.get('code_challenge_method'),'S256');const raw=url.searchParams.get('state');const original=globalThis.fetch;globalThis.fetch=async(url)=>String(url).includes('access_token')?Response.json({access_token:'temporary-test'}):Response.json({id:'unapproved'});try{const req=new Request(`https://admin.alhuzali.com/auth/callback?state=${raw}&code=test`,{headers:{Cookie:'__Host-portfolio_oauth='+raw}});assert.equal((await worker.fetch(req,v)).status,403)}finally{globalThis.fetch=original}});
test('logout invalidates the server session',async()=>{const v=await env();assert.equal((await call('/auth/logout',v,{method:'POST'})).status,200);assert.equal((await call('/api/content',v)).status,401)});
