import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {readFile} from 'node:fs/promises';
import {home,projects,detail,shell} from '../src/render.mjs';
import seed from '../content/portfolio.json' with {type:'json'};
const js=await readFile(new URL('../public/site.js',import.meta.url),'utf8');
function page(body,path='/'){const dom=new JSDOM(shell(seed,body,'Test','Test',path),{url:'https://alhuzali.com'+path,runScripts:'outside-only'});dom.window.eval(js);return dom}
test('project search and combined filters update visible cards and shared query state',()=>{const dom=page(projects(seed),'/projects/');const{document:d,Event}=dom.window;const visible=()=>[...d.querySelectorAll('.project-card')].filter(c=>!c.hidden);assert.equal(visible().length,4);d.querySelector('#category-filter').value='Project management';d.querySelector('#category-filter').dispatchEvent(new Event('change',{bubbles:true}));assert.equal(visible().length,2);d.querySelector('#project-search').value='planning';d.querySelector('#project-search').dispatchEvent(new Event('input',{bubbles:true}));assert.equal(visible().length,1);assert.match(dom.window.location.search,/q=planning/);d.querySelector('#type-filter').value='interactive';d.querySelector('#type-filter').dispatchEvent(new Event('change',{bubbles:true}));assert.equal(visible().length,0);assert.equal(d.querySelector('#empty-results').hidden,false);dom.window.close()});
test('mobile navigation toggles and closes when a destination is selected',()=>{const dom=page(home(seed));const d=dom.window.document;const button=d.querySelector('.menu-button');button.click();assert.equal(button.getAttribute('aria-expanded'),'true');assert.ok(d.querySelector('#main-nav').classList.contains('open'));d.querySelector('#main-nav a[href="/#about"]').click();assert.equal(button.getAttribute('aria-expanded'),'false');dom.window.close()});
test('Power BI is loaded only on request and selects a mobile-specific URL',()=>{const d=structuredClone(seed),p=d.projects[0];p.type='interactive';p.embedUrl='https://app.powerbi.com/view?r=desktop';p.mobileEmbedUrl='https://app.powerbi.com/view?r=mobile';const dom=page(detail(d,p),'/ntdp-intelligence/');Object.defineProperty(dom.window,'innerWidth',{value:390});assert.equal(dom.window.document.querySelectorAll('iframe').length,0);dom.window.document.querySelector('#load-report').click();assert.equal(dom.window.document.querySelector('iframe').src,p.mobileEmbedUrl);assert.match(dom.window.document.querySelector('iframe').title,/Power BI/);dom.window.close()});
test('admin editor loads saved data and saves changes through the protected API',async()=>{const html=await readFile(new URL('../admin/index.html',import.meta.url),'utf8');const js=await readFile(new URL('../admin/admin.js',import.meta.url),'utf8');const dom=new JSDOM(html,{url:'https://admin.alhuzali.com',runScripts:'outside-only'});let saved;dom.window.structuredClone=structuredClone;dom.window.fetch=async(path,opt={})=>({ok:true,json:async()=>path==='/api/session'?{configured:true,authenticated:true,csrf:'verified-test'}:opt.method==='PUT'?(saved=JSON.parse(opt.body),{content:saved.content,revision:2}):{content:structuredClone(seed),revision:1}});dom.window.eval(js);await new Promise(r=>setTimeout(r,15));const d=dom.window.document;assert.ok(d.querySelector('.studio-header'));d.querySelector('[data-nav="profile"]').click();const input=d.querySelector('[data-path="profile.headline"]');input.value='Updated headline';input.dispatchEvent(new dom.window.Event('input',{bubbles:true}));d.querySelector('[data-save]').click();await new Promise(r=>setTimeout(r,15));assert.equal(saved.content.profile.headline,'Updated headline');assert.equal(d.querySelector('.save-status').textContent,'Draft saved');d.querySelector('[data-nav="projects"]').click();d.querySelector('[data-edit-project="0"]').click();assert.ok(d.querySelector('[data-path="projects.0.audience"]'));dom.window.close()});
test('unconfigured admin offers no fake working sign-in',async()=>{const html=await readFile(new URL('../admin/index.html',import.meta.url),'utf8');const js=await readFile(new URL('../admin/admin.js',import.meta.url),'utf8');const dom=new JSDOM(html,{url:'https://admin.alhuzali.com',runScripts:'outside-only'});dom.window.fetch=async()=>({ok:true,json:async()=>({configured:false,authenticated:false})});dom.window.eval(js);await new Promise(r=>setTimeout(r,15));assert.equal(dom.window.document.querySelector('#sign-in').hidden,true);assert.match(dom.window.document.querySelector('#login-state').textContent,/locked/);dom.window.close()});
test('structured project filter uses the same visible state and rejects invalid options',async()=>{const dom=new JSDOM(shell(seed,projects(seed),'Test','Test','/projects/'),{url:'https://alhuzali.com/projects/',runScripts:'outside-only'});let tool;Object.defineProperty(dom.window.document,'modelContext',{value:{registerTool(t){tool=t}}});dom.window.eval(js);const result=tool.execute({topic:'Project management'});assert.equal(result.projects.length,2);assert.equal(dom.window.document.querySelector('#category-filter').value,'Project management');assert.throws(()=>tool.execute({topic:'Nonexistent topic'}),/Unknown/);assert.equal(dom.window.document.querySelector('#category-filter').value,'Project management');dom.window.close()});
