import {validatePortfolio,publicPortfolio,preserveSlugs} from '../src/schema.mjs';
export const REPO='hussamalhuzali/alhuzali-portfolio', OWNER=94220344;
const CONTENT='content/portfolio.json', BASE=`/repos/${REPO}`;
const decode=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
const encode=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)};
export function browserStore(){let db;const open=()=>db?Promise.resolve(db):new Promise((resolve,reject)=>{const r=indexedDB.open('alhuzali-studio',1);r.onupgradeneeded=()=>r.result.createObjectStore('draft');r.onsuccess=()=>resolve(db=r.result);r.onerror=()=>reject(r.error)});return {async get(){const d=await open();return new Promise((resolve,reject)=>{const r=d.transaction('draft').objectStore('draft').get('owner');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})},async put(value){const d=await open();return new Promise((resolve,reject)=>{const t=d.transaction('draft','readwrite');t.objectStore('draft').put(value,'owner');t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}}}
export function createBackend({request=fetch,storage=browserStore()}={}){
 let token='',state=null,authed=false,working=false;
 async function gh(path,method='GET',body){if(!token)throw Error('Connect to GitHub first.');const r=await request(`https://api.github.com${path}`,{method,cache:'no-store',credentials:'omit',redirect:'error',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await r.json()}catch{throw Error('GitHub did not return a valid response.')}if(!r.ok){if(r.status===401){token='';authed=false;}throw Error(r.status===409||r.status===422?'The repository changed. Reconnect and review before publishing.':r.status===403?'GitHub denied access. Check that your token has Contents: read and write for alhuzali-portfolio.':r.status===401?'Your GitHub credential has expired or is invalid.':`GitHub request failed (${r.status}).`)}return data}
 const read=()=>gh(`${BASE}/contents/${CONTENT}?ref=main`);
 async function connect(value){token=value.trim();authed=false;try{const u=await gh('/user');if(u.id!==OWNER)throw Error('Only Hussam’s GitHub account can use this studio.');const repo=await gh(BASE);if(!repo.permissions?.push)throw Error('This GitHub account does not have publishing access.');const remote=await read(),content=JSON.parse(decode(remote.content));validatePortfolio(content);const cached=await storage.get();if(cached){if(cached.baseSha!==remote.sha){throw Error('A saved draft is based on an older publication. Export or clear the local draft before reconnecting to avoid overwriting newer work.');}validatePortfolio(cached.content);state=cached;}else state={content,baseSha:remote.sha,revision:0,files:[],publishedAt:'',commit:''};authed=true;return true}catch(e){token='';authed=false;throw e}}
 async function persist(){await storage.put(structuredClone(state))}
 async function publish(){if(working)throw Error('Publishing is already in progress.');working=true;try{const output=publicPortfolio(validatePortfolio(state.content));for(const p of output.projects)for(const d of p.documents)if(!d.url)throw Error('Every published document needs a file or URL.');const head=await gh(`${BASE}/git/ref/heads/main`);const current=await gh(`${BASE}/contents/${CONTENT}?ref=${head.object.sha}`);if(current.sha!==state.baseSha)throw Error('Published content changed in GitHub. Export your draft, clear it, and reconnect before publishing.');const commit=await gh(`${BASE}/git/commits/${head.object.sha}`),serialized=JSON.stringify(output,null,2)+'\n';const refs=new Set();const walk=v=>{if(typeof v==='string')refs.add(v);else if(v&&typeof v==='object')Object.values(v).forEach(walk)};walk(output);const entries=[];for(const file of state.files.filter(f=>refs.has(f.url))){const blob=await gh(`${BASE}/git/blobs`,'POST',{content:encode(new Uint8Array(file.bytes)),encoding:'base64'});entries.push({path:file.path,mode:'100644',type:'blob',sha:blob.sha})}const blob=await gh(`${BASE}/git/blobs`,'POST',{content:serialized,encoding:'utf-8'});entries.push({path:CONTENT,mode:'100644',type:'blob',sha:blob.sha});const tree=await gh(`${BASE}/git/trees`,'POST',{base_tree:commit.tree.sha,tree:entries});const next=await gh(`${BASE}/git/commits`,'POST',{message:'Update portfolio from Portfolio Studio',tree:tree.sha,parents:[head.object.sha]});await gh(`${BASE}/git/refs/heads/main`,'PATCH',{sha:next.sha,force:false});state.baseSha=blob.sha;state.commit=next.sha;state.publishedAt=new Date().toISOString();state.files=state.files.filter(f=>!refs.has(f.url));await persist();return {commit:next.sha,publishedAt:state.publishedAt};}finally{working=false}}
 async function upload(file){if(file.size>10*1024*1024)throw Error('Maximum file size is 10 MB.');if(state.files.reduce((n,f)=>n+f.bytes.byteLength,0)+file.size>40*1024*1024)throw Error('Publish or remove pending files before adding more than 40 MB.');const ext=file.name.split('.').pop().toLowerCase(),bytes=new Uint8Array(await file.arrayBuffer());const allowed=['pdf','pptx','docx','xlsx','csv','txt','png','jpg','jpeg','webp'];if(!allowed.includes(ext))throw Error('Unsupported file type.');const sig=String.fromCharCode(...bytes.slice(0,12));if(ext==='pdf'&&!sig.startsWith('%PDF-')||['pptx','docx','xlsx'].includes(ext)&&!sig.startsWith('PK')||ext==='png'&&!(bytes[0]===137&&sig.slice(1,4)==='PNG')||['jpg','jpeg'].includes(ext)&&!(bytes[0]===255&&bytes[1]===216)||ext==='webp'&&!(sig.startsWith('RIFF')&&sig.slice(8)==='WEBP'))throw Error('The file content does not match its extension.');const name=crypto.randomUUID()+'.'+ext,path='public/uploads/'+name,url='https://alhuzali.com/assets/uploads/'+name;state.files.push({path,url,bytes:bytes.buffer});await persist();return {url}}
 async function api(path,options={}){if(!authed)throw Error('Connect to GitHub first.');if(path==='/api/session')return {configured:true,authenticated:true,csrf:''};if(path==='/auth/logout'){token='';authed=false;state=null;return {ok:true}}if(path==='/api/content'){if(options.method==='PUT'){const data=JSON.parse(options.body);if(data.revision!==state.revision)throw Error('The draft has changed. Reload before saving.');state.content=validatePortfolio(preserveSlugs(structuredClone(data.content),state.content));state.revision++;await persist()}return structuredClone(state)}if(path==='/api/upload')return upload(options.body);if(path==='/api/publish')return publish();if(path==='/api/deployment'){const runs=await gh(`${BASE}/actions/workflows/pages.yml/runs?per_page=5`);const r=runs.workflow_runs.find(r=>r.head_sha===state.commit)||runs.workflow_runs[0];return {message:r?`Public website: ${r.status}${r.conclusion?' — '+r.conclusion:''}.`:'GitHub has not started a deployment yet.'}}throw Error('Unsupported studio action.')}
 return {connect,api,async exportDraft(){return await storage.get()},async clearDraft(){if(working)throw Error('Wait for publication to finish.');await storage.put(null);state=null;token='';authed=false},previewData(){if(!authed)throw Error('Connect first.');return structuredClone(state)}}
}
