import seed from '../content/portfolio.json' with {type:'json'};
import {validatePortfolio,publicPortfolio,referencedMedia,preserveSlugs} from '../src/schema.mjs';
import {home,projects,detail,shell,e} from '../src/render.mjs';
const COOKIE='__Host-portfolio_session',FLOW='__Host-portfolio_oauth',DAY=86400000;
const enc=new TextEncoder();
const random=()=>{const b=crypto.getRandomValues(new Uint8Array(32));return b64url(b)};
const b64url=b=>btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const hash=async v=>b64url(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v))));
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const cookie=(name,value,age)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
const cookies=req=>Object.fromEntries((req.headers.get('Cookie')||'').split(';').map(v=>v.trim().split('=')));
const redirect=(url,extra={})=>new Response(null,{status:302,headers:{Location:url,'Cache-Control':'no-store',...extra}});
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const configured=env=>!!(env.DB&&env.MEDIA&&env.GITHUB_CLIENT_ID&&env.GITHUB_CLIENT_SECRET&&env.GITHUB_CONTENT_TOKEN&&env.OWNER_GITHUB_ID&&env.ADMIN_ORIGIN&&env.GITHUB_OWNER&&env.GITHUB_REPO);
function secured(response){const r=new Response(response.body,response);r.headers.set('X-Content-Type-Options','nosniff');r.headers.set('Referrer-Policy','strict-origin-when-cross-origin');r.headers.set('X-Frame-Options','SAMEORIGIN');r.headers.set('X-Robots-Tag','noindex, nofollow');r.headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');r.headers.set('Strict-Transport-Security','max-age=31536000');if(!r.headers.has('Content-Security-Policy'))r.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https: data:; frame-src 'self' https:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'");return r}
async function session(req,env){const token=cookies(req)[COOKIE];if(!token||!/^[A-Za-z0-9_-]{43}$/.test(token)||!env.DB)return null;const row=await env.DB.prepare('SELECT * FROM sessions WHERE id = ? AND expires_at > ?').bind(await hash(token),Date.now()).first();if(!row||row.user_id!==String(env.OWNER_GITHUB_ID))return null;return row}
async function owner(req,env,write=false){if(!configured(env))throw new HttpError(503,'Secure admin configuration is incomplete.');const s=await session(req,env);if(!s)throw new HttpError(401,'Sign in with the portfolio owner’s GitHub account.');if(write&&(req.headers.get('Origin')!==env.ADMIN_ORIGIN||req.headers.get('X-CSRF-Token')!==s.csrf))throw new HttpError(403,'This request could not be verified. Reload the studio and try again.');return s}
async function readBounded(req,limit){if(Number(req.headers.get('Content-Length'))>limit)throw new HttpError(413,'File or content exceeds the size limit.');const reader=req.body?.getReader();if(!reader)return new Uint8Array();let size=0;const chunks=[];while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();throw new HttpError(413,'File or content exceeds the size limit.')}chunks.push(value)}const out=new Uint8Array(size);let at=0;for(const chunk of chunks){out.set(chunk,at);at+=chunk.length}return out}
async function body(req){try{return JSON.parse(new TextDecoder().decode(await readBounded(req,800000)))}catch(err){if(err instanceof HttpError)throw err;throw new HttpError(400,'Invalid JSON content.')}}
async function state(env){await env.DB.prepare("INSERT OR IGNORE INTO studio_content (id, draft, revision) VALUES ('portfolio', ?, 1)").bind(JSON.stringify(seed)).run();return env.DB.prepare("SELECT * FROM studio_content WHERE id = 'portfolio'").first()}
async function gh(env,path,options={}){const r=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${env.GITHUB_CONTENT_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'Alhuzali-Portfolio-Studio',...options.headers}});if(!r.ok)throw new HttpError(r.status===409?409:502,r.status===409?'The repository changed. Try publishing again.':'GitHub could not complete the request. Check repository access and the publishing token.');return r.json()}
const repo=env=>`/repos/${encodeURIComponent(env.GITHUB_OWNER)}/${encodeURIComponent(env.GITHUB_REPO)}`;
const utf8Base64=s=>{const bytes=enc.encode(s);let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text)};
const unbase64=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
export function detectFile(bytes,name){const ext=name.toLowerCase().split('.').pop(),starts=seq=>seq.every((v,i)=>bytes[i]===v);if(ext==='pdf'&&starts([37,80,68,70,45]))return{mime:'application/pdf',inline:true};if(ext==='png'&&starts([137,80,78,71,13,10,26,10]))return{mime:'image/png',inline:true};if(['jpg','jpeg'].includes(ext)&&starts([255,216,255]))return{mime:'image/jpeg',inline:true};if(ext==='webp'&&new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')return{mime:'image/webp',inline:true};if(['pptx','docx','xlsx'].includes(ext)&&starts([80,75,3,4]))return{mime:({pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})[ext],inline:false};if(['txt','csv'].includes(ext)&&!bytes.includes(0))return{mime:ext==='csv'?'text/csv':'text/plain',inline:false};throw new HttpError(400,'Supported files: PDF, PNG, JPEG, WebP, PPTX, DOCX, XLSX, CSV, or TXT. The file contents must match its extension.')}
async function route(req,env){const u=new URL(req.url),path=u.pathname;
 if(path==='/api/session'&&req.method==='GET'){const ready=configured(env),s=ready?await session(req,env):null;return json({configured:ready,authenticated:!!s,...(s?{csrf:s.csrf}:{})})}
 if(path==='/auth/login'&&req.method==='GET'){if(!configured(env))throw new HttpError(503,'Secure admin setup is not connected yet.');if(u.origin!==env.ADMIN_ORIGIN)throw new HttpError(400,'Use the configured admin address to sign in.');const raw=random(),stateKey=await hash(raw),verifier=random(),challenge=await hash(verifier);await env.DB.batch([env.DB.prepare('DELETE FROM oauth_attempts WHERE expires_at < ?').bind(Date.now()),env.DB.prepare('DELETE FROM sessions WHERE expires_at < ?').bind(Date.now()),env.DB.prepare('INSERT INTO oauth_attempts (state, verifier, expires_at) VALUES (?, ?, ?)').bind(stateKey,verifier,Date.now()+600000)]);const target=new URL('https://github.com/login/oauth/authorize');for(const[k,v]of Object.entries({client_id:env.GITHUB_CLIENT_ID,redirect_uri:env.ADMIN_ORIGIN+'/auth/callback',state:raw,scope:'',allow_signup:'false',code_challenge:challenge,code_challenge_method:'S256'}))target.searchParams.set(k,v);return redirect(target.toString(),{'Set-Cookie':cookie(FLOW,raw,600)})}
 if(path==='/auth/callback'&&req.method==='GET'){if(!configured(env))throw new HttpError(503,'Secure admin setup is incomplete.');if(u.origin!==env.ADMIN_ORIGIN)throw new HttpError(400,'Unexpected sign-in address.');const raw=u.searchParams.get('state');if(!raw||raw!==cookies(req)[FLOW]||!u.searchParams.get('code'))throw new HttpError(403,'Sign-in could not be verified. Start again from the studio.');const attempt=await env.DB.prepare('DELETE FROM oauth_attempts WHERE state = ? AND expires_at > ? RETURNING *').bind(await hash(raw),Date.now()).first();if(!attempt)throw new HttpError(403,'The sign-in link has expired. Start again.');const tokenResponse=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:env.GITHUB_CLIENT_ID,client_secret:env.GITHUB_CLIENT_SECRET,code:u.searchParams.get('code'),redirect_uri:env.ADMIN_ORIGIN+'/auth/callback',code_verifier:attempt.verifier})});if(!tokenResponse.ok)throw new HttpError(502,'GitHub sign-in is temporarily unavailable.');const token=await tokenResponse.json();if(!token.access_token)throw new HttpError(403,'GitHub did not authorize this sign-in.');const userResponse=await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${token.access_token}`,Accept:'application/vnd.github+json','User-Agent':'Alhuzali-Portfolio-Studio'}});if(!userResponse.ok)throw new HttpError(403,'Could not verify your GitHub identity.');const user=await userResponse.json();if(String(user.id)!==String(env.OWNER_GITHUB_ID))throw new HttpError(403,'Only the portfolio owner can access this studio.');const sessionToken=random();const old=cookies(req)[COOKIE];if(old)await env.DB.prepare('DELETE FROM sessions WHERE id = ?').bind(await hash(old)).run();await env.DB.prepare('INSERT INTO sessions (id, user_id, csrf, expires_at) VALUES (?, ?, ?, ?)').bind(await hash(sessionToken),String(user.id),random(),Date.now()+7*DAY).run();const r=redirect(env.ADMIN_ORIGIN+'/');r.headers.append('Set-Cookie',cookie(COOKIE,sessionToken,7*86400));r.headers.append('Set-Cookie',cookie(FLOW,'',0));return r}
 if(path==='/auth/logout'&&req.method==='POST'){const s=await owner(req,env,true);await env.DB.prepare('DELETE FROM sessions WHERE id = ?').bind(s.id).run();const r=json({ok:true});r.headers.set('Set-Cookie',cookie(COOKIE,'',0));return r}
 if(path==='/api/content'){await owner(req,env,req.method!=='GET');const current=await state(env);if(req.method==='GET')return json({content:JSON.parse(current.draft),revision:current.revision,publishedAt:current.published_at,commit:current.commit_sha});if(req.method==='PUT'){const input=await body(req);let next;try{next=preserveSlugs(input.content,JSON.parse(current.draft));validatePortfolio(next)}catch(err){throw new HttpError(400,err.message)}if(input.revision!==current.revision)throw new HttpError(409,'This draft changed in another session. Reload before saving to avoid overwriting it.');const result=await env.DB.prepare("UPDATE studio_content SET draft = ?, revision = revision + 1 WHERE id = 'portfolio' AND revision = ? AND (publish_lock IS NULL OR publish_lock_at < ?)").bind(JSON.stringify(next),input.revision,Date.now()-600000).run();if(result.meta.changes!==1)throw new HttpError(409,'Another save or publication is in progress. Try again shortly.');return json({content:next,revision:current.revision+1})}}
 if(path==='/api/upload'&&req.method==='POST'){await owner(req,env,true);let filename;try{filename=decodeURIComponent(req.headers.get('X-File-Name')||'')}catch{throw new HttpError(400,'Invalid file name.')}filename=filename.replace(/[^a-zA-Z0-9._-]/g,'-').slice(-120);if(!filename)throw new HttpError(400,'Choose a file to upload.');const bytes=await readBounded(req,10*1024*1024);if(!bytes.length)throw new HttpError(400,'The file is empty.');const type=detectFile(bytes,filename),key=`${crypto.randomUUID()}-${filename}`;await env.MEDIA.put(key,bytes,{httpMetadata:{contentType:type.mime},customMetadata:{filename,inline:String(type.inline)}});return json({url:`${env.ADMIN_ORIGIN}/media/${key}`,filename},201)}
 if(path.startsWith('/media/')&&['GET','HEAD'].includes(req.method)){if(!env.DB||!env.MEDIA)throw new HttpError(503,'Media is not configured.');const key=path.slice(7);if(!/^[a-zA-Z0-9._-]+$/.test(key))throw new HttpError(404,'File not found.');const current=await state(env);const visible=current.published&&referencedMedia(JSON.parse(current.published)).has(key);if(!visible&&!await session(req,env))throw new HttpError(404,'File not found.');const obj=await env.MEDIA.get(key);if(!obj)throw new HttpError(404,'File not found.');const h=new Headers();obj.writeHttpMetadata(h);h.set('Cache-Control',visible?'public, max-age=300':'private, no-store');h.set('ETag',obj.httpEtag);h.set('Content-Disposition',`${obj.customMetadata?.inline==='true'?'inline':'attachment'}; filename="${obj.customMetadata?.filename||'document'}"`);h.set('Content-Security-Policy',"default-src 'none'; frame-ancestors 'self' https://alhuzali.com https://www.alhuzali.com; sandbox");h.set('Access-Control-Allow-Origin',env.PUBLIC_ORIGIN);const r=new Response(req.method==='HEAD'?null:obj.body,{headers:h});r.headers.set('X-Content-Type-Options','nosniff');return r}
 if(path==='/api/publish'&&req.method==='POST'){await owner(req,env,true);const input=await body(req),current=await state(env);if(current.revision!==input.revision)throw new HttpError(409,'The draft changed. Save it again before publishing.');const draft=JSON.parse(current.draft);try{validatePortfolio(draft)}catch(err){throw new HttpError(400,err.message)}const output=publicPortfolio(draft),lock=random();const acquired=await env.DB.prepare("UPDATE studio_content SET publish_lock = ?, publish_lock_at = ? WHERE id = 'portfolio' AND revision = ? AND (publish_lock IS NULL OR publish_lock_at < ?)").bind(lock,Date.now(),input.revision,Date.now()-600000).run();if(acquired.meta.changes!==1)throw new HttpError(409,'A publication is already in progress.');try{for(const key of referencedMedia(output)){if(!await env.MEDIA.head(key))throw new HttpError(400,'A referenced upload is missing. Replace the file before publishing.')}const route=`${repo(env)}/contents/content/portfolio.json`;const existing=await gh(env,route+'?ref='+encodeURIComponent(env.GITHUB_BRANCH||'main'));const existingData=JSON.parse(unbase64(existing.content));const expected=current.published?JSON.parse(current.published):publicPortfolio(seed);if(JSON.stringify(existingData)!==JSON.stringify(expected)&&JSON.stringify(existingData)!==JSON.stringify(output))throw new HttpError(409,'Portfolio content was edited directly in GitHub. Reconcile that change before publishing from the studio.');const result=await gh(env,route,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update portfolio content from Portfolio Studio',content:utf8Base64(JSON.stringify(output,null,2)+'\n'),sha:existing.sha,branch:env.GITHUB_BRANCH||'main'})});const publishedAt=new Date().toISOString();await env.DB.prepare("UPDATE studio_content SET published = ?, published_at = ?, commit_sha = ? WHERE id = 'portfolio' AND publish_lock = ?").bind(JSON.stringify(output),publishedAt,result.commit.sha,lock).run();return json({publishedAt,commit:result.commit.sha,message:'Submitted to GitHub. Await the Pages deployment.'})}finally{await env.DB.prepare("UPDATE studio_content SET publish_lock = NULL, publish_lock_at = NULL WHERE id = 'portfolio' AND publish_lock = ?").bind(lock).run()}}
 if(path==='/api/deployment'&&req.method==='GET'){await owner(req,env);const c=await state(env);if(!c.commit_sha)return json({message:'No studio publication yet.'});const data=await gh(env,`${repo(env)}/actions/runs?head_sha=${encodeURIComponent(c.commit_sha)}&per_page=20`);const run=data.workflow_runs?.find(r=>r.name==='Publish portfolio');return json({message:!run?'Publication submitted; GitHub has not started the build yet.':run.status!=='completed'?`GitHub deployment: ${run.status.replaceAll('_',' ')}.`:run.conclusion==='success'?'The latest portfolio publication deployed successfully.':`Deployment finished with status: ${run.conclusion}. Check the workflow in GitHub.`})}
 if(path==='/preview'||path.startsWith('/preview/')){await owner(req,env);const c=await state(env),d=JSON.parse(c.draft);d.projects.forEach(p=>p.published=true);d.sections.forEach(s=>s.published=true);const slug=path.replace(/^\/preview\/?/,'').replace(/\/$/,'');const p=d.projects.find(p=>p.slug===slug);const view=slug===''?home(d):slug==='projects'?projects(d):p?detail(d,p):null;if(!view)throw new HttpError(404,'Project not found.');let html=shell(d,view,'Draft preview — '+d.profile.name,d.profile.summary);html=html.replace(/href="\/(?!assets\/)([^"#]*)/g,'href="/preview/$1').replace('<body>','<body><div style="padding:12px;text-align:center;background:#fff1ce;color:#674f18;font-size:14px">Private draft preview · Includes unpublished projects and sections</div>');return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store'}})}
 if(path.startsWith('/api/')||path.startsWith('/auth/'))throw new HttpError(404,'Endpoint not found.');
 if(!['GET','HEAD'].includes(req.method))throw new HttpError(405,'Method not allowed.');
 if(env.ASSETS){const asset=await env.ASSETS.fetch(req);const response=new Response(asset.body,asset);response.headers.set('Cache-Control','no-store');return response}return json({error:'Admin assets are not deployed.'},503);
}
export default{async fetch(req,env){try{const r=await route(req,env);if(new URL(req.url).pathname.startsWith('/media/'))return r;return secured(r)}catch(err){return secured(json({error:err instanceof HttpError?err.message:'The request could not be completed. Please try again.'},err.status||500))}}};
