export const RESERVED=new Set(['projects','admin','api','auth','assets','media','preview','404','robots','sitemap','favicon','index']);
export function safeUrl(value,{image=false,embed=false}={}){if(!value)return true;if(typeof value!=='string'||value.length>3000)return false;if(embed){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='app.powerbi.com'&&['/view','/reportEmbed'].includes(u.pathname)&&!u.username&&!u.password}catch{return false}}if(value.startsWith('/assets/')&&!value.includes('..')&&!/[\\<>"']/.test(value))return true;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!image||!u.pathname.toLowerCase().endsWith('.svg'))}catch{return false}}
const fail=m=>{throw new Error(m)};
function str(v,label,max=5000,required=false){if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail(`${label} must be ${required?'non-empty ':''}text of up to ${max} characters.`)}
function arr(v,label,max=100){if(!Array.isArray(v)||v.length>max)fail(`${label} must contain at most ${max} items.`)}
function strings(v,label,max=30){arr(v,label,max);v.forEach(s=>str(s,label,2000,true))}
function url(v,label,opts){str(v,label,3000);if(!safeUrl(v,opts))fail(`${label} must be a valid HTTPS URL${opts?.embed?' from app.powerbi.com/view or /reportEmbed':''}.`)}
export function validatePortfolio(d){
 if(!d||d.schemaVersion!==1)fail('Unsupported content format.');
 const p=d.profile;if(!p)fail('Profile is required.');for(const k of ['name','headline','summary','about','eyebrow','location'])str(p[k],`Profile ${k}`,k==='about'?8000:1200,true);
 str(p.email,'Email',200,true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email)||/[<>"']/.test(p.email))fail('Enter a valid email address.');for(const k of ['linkedin','resume'])url(p[k],k);url(p.photo,'Profile photo',{image:true});strings(p.credentials,'Credentials',10);
 arr(d.capabilities,'Capabilities',12);d.capabilities.forEach(c=>{str(c.title,'Capability title',120,true);str(c.description,'Capability description',2000,true);strings(c.tools,'Capability tools',20)});
 arr(d.experience,'Experience',30);d.experience.forEach(x=>{for(const k of ['role','organization','period','type','focus'])str(x[k],`Experience ${k}`,500,k!=='focus');strings(x.points,'Experience highlights',12)});
 arr(d.education,'Education',15);d.education.forEach(x=>{for(const k of ['degree','institution','period'])str(x[k],`Education ${k}`,500,true)});
 arr(d.certificates,'Certificates',60);d.certificates.forEach(c=>{for(const k of ['name','issuer','status','short'])str(c[k],`Certificate ${k}`,500,true);url(c.url,'Certificate link')});
 arr(d.sections,'Sections',20);d.sections.forEach(s=>{str(s.title,'Section title',200,true);str(s.label,'Section label',100);str(s.body,'Section body',15000);if(typeof s.published!=='boolean')fail('Section visibility must be true or false.')});
 arr(d.projects,'Projects',80);const ids=new Set(),slugs=new Set();for(const x of d.projects){str(x.id,'Project identifier',100,true);if(!/^[a-zA-Z0-9_-]+$/.test(x.id)||ids.has(x.id))fail('Project identifiers must be unique.');ids.add(x.id);const aliases=x.previousSlugs||[];arr(aliases,'Previous URLs',30);for(const s of [x.slug,...aliases]){if(typeof s!=='string'||s.length>90||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s)||RESERVED.has(s)||slugs.has(s))fail(`Project URL “${s}” is invalid, reserved, or already used.`);slugs.add(s)}for(const k of ['title','brief','category','audience','role'])str(x[k],`Project ${k}`,2000,true);for(const k of ['body','outcome','note'])str(x[k],`Project ${k}`,20000);strings(x.tools,'Project tools',25);strings(x.insights,'Key insights',15);if(!['interactive','documentation'].includes(x.type))fail('Select a valid project format.');if(!['public','secure'].includes(x.embedMode))fail('Select a valid embed mode.');for(const k of ['published','featured'])if(typeof x[k]!=='boolean')fail('Project visibility must be true or false.');url(x.embedUrl,'Power BI URL',{embed:true});url(x.mobileEmbedUrl,'Mobile report URL',{embed:true});if(x.type==='interactive'&&!x.embedUrl)fail('Interactive projects need a Power BI embed URL.');if(x.type==='documentation'&&(x.embedUrl||x.mobileEmbedUrl))fail('Choose Interactive to attach a live report.');if(x.embedMode==='public'&&x.embedUrl&&new URL(x.embedUrl).pathname!=='/view')fail('Public mode needs a Publish to web /view URL.');if(x.embedMode==='secure'&&x.embedUrl&&new URL(x.embedUrl).pathname!=='/reportEmbed')fail('Microsoft sign-in mode needs a /reportEmbed URL.');url(x.cover,'Cover image',{image:true});arr(x.documents,'Documents',30);x.documents.forEach(f=>{str(f.title,'Document title',300,true);str(f.kind,'Document type',50,true);url(f.url,'Document URL')});}
 if(JSON.stringify(d).length>750000)fail('Content is too large.');return d;
}
export function publicPortfolio(d){const c=structuredClone(d);c.projects=c.projects.filter(p=>p.published);c.sections=c.sections.filter(s=>s.published);return c}
export function referencedMedia(d){const refs=new Set();const walk=v=>{if(typeof v==='string'){try{const u=new URL(v);if(u.pathname.startsWith('/media/'))refs.add(u.pathname.slice(7))}catch{}}else if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')Object.values(v).forEach(walk)};walk(d);return refs}
export function preserveSlugs(next,old){const previous=new Map(old.projects.map(p=>[p.id,p]));for(const p of next.projects){const before=previous.get(p.id);if(before){p.previousSlugs=[...new Set([...(before.previousSlugs||[]),...(p.previousSlugs||[]),...(before.slug!==p.slug?[before.slug]:[])])].filter(s=>s!==p.slug)}}return next}
